行列積の実装
テキストの目的
数式演算ライブラリのNumPyに慣れる
行列演算に慣れる


In [ ]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。


計算過程もマークダウンテキストを用いて説明してください。

AB=[[-1, 2, 3], [4, -5, 6], [7, 8, -9]]
[[0, 2, 1], [0, 2, -8], [2, 9, -1]]

=[[3*2 -2+4+27 -1-16-3],[12 8-10+54 4+40-6],
[-18 14+16-81 7-64+9]]

=[[6 29 -20],[12 52 38],[-18 -51 48]]

【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、

または@演算子を使うことで簡単に計算できます。
これらを使い行列積を計算してください。



In [ ]:
print(np.matmul(a_ndarray,b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。


行列Aの(0,0)の要素 
a
0
,
0
 と行列Bの(0,0)の要素 
b
0
,
0
 を掛け合わせる
行列Aの(0,1)の要素 
a
0
,
1
 と行列Bの(1,0)の要素 
b
1
,
0
 を掛け合わせる
行列Aの(0,2)の要素 
a
0
,
2
 と行列Bの(2,0)の要素 
b
2
,
0
 を掛け合わせる
それらの値をすべて足し合わせる

数式で表すと


2
∑
k
=
0
 
a
0
,
k
b
k
,
0

です。この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [ ]:
#コード02
import numpy as np

a = np.array([[-1., 2., 3.],
              [4., -5., 6.],
              [7., 8., -9.]])
b =  np.array([[0., 2., 1],
               [0., 2., -8],
               [2., 9., -1]])
x = np.zeros((3, 3))
ii = 3
kk = 3
jj = 3

for i in range(ii):
    for j in range(jj):
        for k in range(kk):
            x[i][j] = x[i][j] + a[i][k] * b[k][j]
print(x)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。


行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


計算結果である $3 \times 3$ の行列Cの各要素 $c_{i, j}$ は数式で表すと次のようになります。


\[c_{i,j} = \sum^{2}_{k=0}a_{i,k}b_{k,j}\]
for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス $i$ や $j$ を1増やすと、次の行や列に移ることができます。



In [1]:
import numpy as np

def Matrix_product(a,b):
  x = np.zeros((3, 3))
  ii = 3
  kk = 3
  jj = 3

  for i in range(ii):
      for j in range(jj):
          for k in range(kk):
              x[i][j] = x[i][j] + a[i][k] * b[k][j]
  print(x)


a = np.array([[-1., 2., 3.],
              [4., -5., 6.],
              [7., 8., -9.]])
b =  np.array([[0., 2., 1],
               [0., 2., -8],
               [2., 9., -1]])
Matrix_product(a,b)


[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。


if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [4]:
import numpy as np

def Matrix_product(a,b):
  # 行列の大きさ
  # print("行列aの大きさ:", a.shape)
  # print("行列aの行数:", a.shape[0])
  # print("行列aの列数:", a.shape[1])
  # print("行列bの大きさ:", b.shape)
  # print("行列bの行数:", b.shape[0])
  # print("行列bの列数:", b.shape[1])
  if(a.shape[1]==b.shape[0]):
    x = np.zeros((3, 3))
    ii = 3
    kk = 3
    jj = 3

    for i in range(ii):
        for j in range(jj):
            for k in range(kk):
                x[i][j] = x[i][j] + a[i][k] * b[k][j]
    print("行列積の計算可能")
    print(x)
  else:
    print("行列積の計算不可能")


a = np.array([[-1., 2., 3.],
              [4., -5., 6.],
              [7., 8., -9.]])
b =  np.array([[0., 2., 1],
               [0., 2., -8],
               [2., 9., -1]])
Matrix_product(a,b)

d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
Matrix_product(d_ndarray_,e_ndarray)


行列積の計算可能
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
行列積の計算不可能


【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。


np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [13]:
import numpy as np

def Matrix_product(a,b):
  if(a.shape[1]==b.shape[0]):
    x = np.zeros((2, 2))
    ii = 2
    kk = 3
    jj =2

    for i in range(ii):
        for j in range(jj):
            for k in range(kk):
                x[i][j] = x[i][j] + a[i][k] * b[k][j]
    print("行列積の計算可能")
    print(x)
  else:
    print("行列積の計算不可能")



d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print(np.transpose(e_ndarray))
Matrix_product(d_ndarray_,np.transpose(e_ndarray))

d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print(e_ndarray.T)
Matrix_product(d_ndarray_,e_ndarray.T)


[[-9  6]
 [ 8 -5]
 [ 7  4]]
行列積の計算可能
[[ 46.  -4.]
 [-34.  73.]]
[[-9  6]
 [ 8 -5]
 [ 7  4]]
行列積の計算可能
[[ 46.  -4.]
 [-34.  73.]]
