テキストの目的
クラスを利用したコードを読み書きできるようにする

どのように学ぶか
これまで使用してきたクラスを元にしてオブジェクト指向を理解していきます。



【問題1】これまで利用してきたクラスの列挙
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。


Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。



from sklearn.preprocessing import StandardScaler
StandardScaler（標準化クラス）
from sklearn.neighbors import KNeighborsClassifier
KNeighborsClassifier（最近傍法）
from sklearn.linear_model import LogisticRegression
LogisticRegression（ロジスティック回帰クラス）
from sklearn.svm import SVC
SVC（SVCクラス）
from sklearn.tree import DecisionTreeClassifier
DecisionTreeClassifier（決定木クラス）
from sklearn.ensemble import RandomForestClassifier
RandomForestClassifier（ランダムフォレストクラス）

from matplotlib.colors import ListedColormap
ListedColormap（カラーマップのクラス）
import matplotlib.pyplot as plt
plt（グラフ化するクラス）

Pandasの2つのデータ型(SeriesとDataFrame)

import pandas as pd
pd（データ分析をするクラス）


【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。


最低でもそれぞれ5つ以上答えてください。


《ndarrayやstrもインスタンス》


ドットをつけるというと、NumPyのndarrayに対してndarray.shapeやndarray.sum()のような使い方は何度も利用してきたかと思います。これは、ndarrayもインスタンスオブジェクトであり、shapeはインスタンス変数、sumはメソッドだったということです。


Pythonのコードに登場するデータはどれもインスタンスオブジェクトであり、listやstrもメソッドを持ちます。

メソッド
変数や値に付けて呼び出すもの
loc、show、transform、fit、scatter、legend、predict、tolist

インスタンス変数	
インスタンスごとに別々に利用する変数
メソッドの内部に記載
type、value、radius、name、age、msg、variable



【問題3】標準化クラスをスクラッチで作成
理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。


今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。


インスタンス変数を作成する際はself.mean_のようにselfを付けます。クラスの外からscaler.mean_と書いていたscalerの部分が自分自身を表すselfになっています。

In [13]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        import statistics
        import numpy as np
        # df = pd.DataFrame(X)
        # data_list = df.values.tolist()
        # self.mean_ = statistics.mean(df)
        # self.var_ = statistics.pstdev(df)
        # a = np.array([0, 1, 2, 3, 4])
        a = np.array(X)
        self.mean_ = a.max()
        self.var_ = a.std()
        pass
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_) / self.var_
        pass
        return X_scaled


import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
# print(X)
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : 5.4
分散 : 1.781684596105607
[[-0.16837997 -1.06640648 -2.24506628 -2.91858616]
 [-0.28063328 -1.34703977 -2.24506628 -2.91858616]
 [-0.3928866  -1.23478645 -2.30119293 -2.91858616]
 [-0.44901326 -1.29091311 -2.18893962 -2.91858616]
 [-0.22450663 -1.01027982 -2.24506628 -2.91858616]
 [ 0.         -0.84189985 -2.0766863  -2.80633284]
 [-0.44901326 -1.12253314 -2.24506628 -2.8624595 ]
 [-0.22450663 -1.12253314 -2.18893962 -2.91858616]
 [-0.56126657 -1.40316642 -2.24506628 -2.91858616]
 [-0.28063328 -1.29091311 -2.18893962 -2.97471281]]


【問題4】 四則演算を行うクラスの作成
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。


コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。


クラス名や説明文も適切に書き換えてください。

In [94]:
class ExampleClass():
    # """
    #   説明用の簡単なクラス
    #   Parameters
    #   ----------
    #   value : float or int
    #       初期値
    #   Attributes
    #   ----------
    #   value : float or int
    #       計算結果
    #   """
  def __init__(self, value):
      self.value = value
      print("初期値{}が設定されました".format(self.value))
  def add(self, value2):#受け取った引数をself.valueに加える
    if(str(self.value).isdigit()):
      self.value += value2
    else:
      print("valueが文字列や配列など数値以外でエラー")
  def minus(self, value2):# 受け取った引数をself.valueから引く
    if(str(self.value).isdigit()):
      self.value -= value2
    else:
      print("valueが文字列や配列など数値以外でエラー")
  def times(self, value2):#受け取った引数でself.valueをかける
    if(str(self.value).isdigit()):
      self.value *= value2
    else:
      print("valueが文字列や配列など数値以外でエラー")
  def divide(self, value2):#受け取った引数でself.valueを割る
    if(str(self.value).isdigit()):
      self.value /= value2
    else:
      print("valueが文字列や配列など数値以外でエラー")

 

example = ExampleClass(7)
print("入力値value : {}".format(example.value))
example.add(3)
print("足し算value : {}".format(example.value))

example.minus(1)
print("引き算value : {}".format(example.value))

example.times(9)
print("掛け算value : {}".format(example.value))

example.divide(2)
print("割り算value : {}".format(example.value))
# else:
#   print("valueが文字列や配列など数値以外でエラー")


初期値7が設定されました
入力値value : 7
足し算value : 10
引き算value : 9
掛け算value : 81
割り算value : 40.5
